# Generated by Django 4.2.7 on 2023-11-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=255)),
                ('special_parking_spaces', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('input_group', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('means_of_non_visual_orientation', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('means_of_acoustic_orientation', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('availability_of_special_elevator', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('sanitary_and_hygienic_premises', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('adapted_warning_devices', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('sign_language_interpreter', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('shelter', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('wi_fi', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('changing_table', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('children_room', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('accompanying_person', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=255)),
                ('phone_call_center', models.CharField(blank=True, default='', max_length=255)),
                ('distance_to_public_transport', models.IntegerField(blank=True, null=True)),
                ('presence_of_tactile_route', models.BooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=False)),
                ('website_institution', models.CharField(blank=True, default='', max_length=255)),
                ('institution_availability_page', models.CharField(blank=True, default='', max_length=255)),
                ('street_name', models.CharField(blank=True, default='', max_length=255)),
                ('house_number', models.CharField(blank=True, default='', max_length=255)),
                ('case_number', models.CharField(blank=True, default='', max_length=255)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.city')),
                ('type_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.typestreet')),
            ],
        ),
    ]
