# Generated by Django 4.2.7 on 2023-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_institutiontype_institution_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectOnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=255)),
                ('type_object', models.CharField(choices=[('ramp', 'пандус'), ('lowered_border', 'понижений бордюр'), ('tactile_marking', 'тактильне маркування'), ('traffic_light_with_sound_signal', 'світлофор зі звуковим сигналом'), ('toilet_for_people_with_disabilities', 'вбиральня для людей з інвалідністю'), ('entrance_level_with_sidewalk', 'вхід в рівень з тротуаром'), ('elevator', 'ліфт'), ('hoist', 'підйомник'), ('space_for_changing_babies', 'простір для сповинання дітей'), ('parking_for_people_with_disabilities', 'парковка для людей з інвалідністю')], default='ramp', max_length=255)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
    ]
